// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84SVLUm4wVYGMMKSL9aR8xILKnJLM0wI',
    appId: '1:54409082043:android:775d9235481e91a7a8659e',
    messagingSenderId: '54409082043',
    projectId: 'split-app-1bb5d',
    storageBucket: 'split-app-1bb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASu8a7palTSGbMt6MFGfPEYnsXLRcF-M0',
    appId: '1:54409082043:ios:e29800d4f54bcfa8a8659e',
    messagingSenderId: '54409082043',
    projectId: 'split-app-1bb5d',
    storageBucket: 'split-app-1bb5d.appspot.com',
    androidClientId: '54409082043-u012gq8rcuv1oscvdjb6repq91qt2c41.apps.googleusercontent.com',
    iosClientId: '54409082043-ap2i1b6k5vh6op728fvcdqotrc2aahv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitApp',
  );
}
